/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.api;

import com.kcjmowright.schwab.trader.model.ServiceError;
import com.kcjmowright.schwab.trader.model.UserPreference;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserPreferenceApi
 */
@Ignore
public class UserPreferenceApiTest {

    private final UserPreferenceApi api = new UserPreferenceApi();

    /**
     * Get user preference information for the logged in user.
     *
     * Get user preference information for the logged in user.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserPreferenceTest() {
        List<UserPreference> response = api.getUserPreference();

        // TODO: test validations
    }
}
