/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AccountOption
 */
public class AccountOption extends AccountsBaseInstrument implements AccountsInstrument {
  @JsonProperty("optionDeliverables")
  private List<AccountAPIOptionDeliverable> optionDeliverables = null;

  /**
   * Gets or Sets putCall
   */
  public enum PutCallEnum {
    PUT("PUT"),
    CALL("CALL"),
    UNKNOWN("UNKNOWN");

    private String value;

    PutCallEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PutCallEnum fromValue(String input) {
      for (PutCallEnum b : PutCallEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("putCall")
  private PutCallEnum putCall = null;

  @JsonProperty("optionMultiplier")
  private Integer optionMultiplier = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    VANILLA("VANILLA"),
    BINARY("BINARY"),
    BARRIER("BARRIER"),
    UNKNOWN("UNKNOWN");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("underlyingSymbol")
  private String underlyingSymbol = null;

  public AccountOption optionDeliverables(List<AccountAPIOptionDeliverable> optionDeliverables) {
    this.optionDeliverables = optionDeliverables;
    return this;
  }

  public AccountOption addOptionDeliverablesItem(AccountAPIOptionDeliverable optionDeliverablesItem) {
    if (this.optionDeliverables == null) {
      this.optionDeliverables = new ArrayList<>();
    }
    this.optionDeliverables.add(optionDeliverablesItem);
    return this;
  }

   /**
   * Get optionDeliverables
   * @return optionDeliverables
  **/
  @Schema(description = "")
  public List<AccountAPIOptionDeliverable> getOptionDeliverables() {
    return optionDeliverables;
  }

  public void setOptionDeliverables(List<AccountAPIOptionDeliverable> optionDeliverables) {
    this.optionDeliverables = optionDeliverables;
  }

  public AccountOption putCall(PutCallEnum putCall) {
    this.putCall = putCall;
    return this;
  }

   /**
   * Get putCall
   * @return putCall
  **/
  @Schema(description = "")
  public PutCallEnum getPutCall() {
    return putCall;
  }

  public void setPutCall(PutCallEnum putCall) {
    this.putCall = putCall;
  }

  public AccountOption optionMultiplier(Integer optionMultiplier) {
    this.optionMultiplier = optionMultiplier;
    return this;
  }

   /**
   * Get optionMultiplier
   * @return optionMultiplier
  **/
  @Schema(description = "")
  public Integer getOptionMultiplier() {
    return optionMultiplier;
  }

  public void setOptionMultiplier(Integer optionMultiplier) {
    this.optionMultiplier = optionMultiplier;
  }

  public AccountOption type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public AccountOption underlyingSymbol(String underlyingSymbol) {
    this.underlyingSymbol = underlyingSymbol;
    return this;
  }

   /**
   * Get underlyingSymbol
   * @return underlyingSymbol
  **/
  @Schema(description = "")
  public String getUnderlyingSymbol() {
    return underlyingSymbol;
  }

  public void setUnderlyingSymbol(String underlyingSymbol) {
    this.underlyingSymbol = underlyingSymbol;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountOption accountOption = (AccountOption) o;
    return Objects.equals(this.optionDeliverables, accountOption.optionDeliverables) &&
        Objects.equals(this.putCall, accountOption.putCall) &&
        Objects.equals(this.optionMultiplier, accountOption.optionMultiplier) &&
        Objects.equals(this.type, accountOption.type) &&
        Objects.equals(this.underlyingSymbol, accountOption.underlyingSymbol) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(optionDeliverables, putCall, optionMultiplier, type, underlyingSymbol, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountOption {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    optionDeliverables: ").append(toIndentedString(optionDeliverables)).append("\n");
    sb.append("    putCall: ").append(toIndentedString(putCall)).append("\n");
    sb.append("    optionMultiplier: ").append(toIndentedString(optionMultiplier)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    underlyingSymbol: ").append(toIndentedString(underlyingSymbol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
