/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AccountNumberHash
 */



public class AccountNumberHash {
  @JsonProperty("accountNumber")
  private String accountNumber = null;

  @JsonProperty("hashValue")
  private String hashValue = null;

  public AccountNumberHash accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @Schema(description = "")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public AccountNumberHash hashValue(String hashValue) {
    this.hashValue = hashValue;
    return this;
  }

   /**
   * Get hashValue
   * @return hashValue
  **/
  @Schema(description = "")
  public String getHashValue() {
    return hashValue;
  }

  public void setHashValue(String hashValue) {
    this.hashValue = hashValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountNumberHash accountNumberHash = (AccountNumberHash) o;
    return Objects.equals(this.accountNumber, accountNumberHash.accountNumber) &&
        Objects.equals(this.hashValue, accountNumberHash.hashValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountNumber, hashValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountNumberHash {\n");

    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
