/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.time.OffsetDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AccountFixedIncome
 */



public class AccountFixedIncome extends AccountsBaseInstrument implements AccountsInstrument {
  @JsonProperty("maturityDate")
  private OffsetDateTime maturityDate = null;

  @JsonProperty("factor")
  private Double factor = null;

  @JsonProperty("variableRate")
  private Double variableRate = null;

  public AccountFixedIncome maturityDate(OffsetDateTime maturityDate) {
    this.maturityDate = maturityDate;
    return this;
  }

   /**
   * Get maturityDate
   * @return maturityDate
  **/
  @Schema(description = "")
  public OffsetDateTime getMaturityDate() {
    return maturityDate;
  }

  public void setMaturityDate(OffsetDateTime maturityDate) {
    this.maturityDate = maturityDate;
  }

  public AccountFixedIncome factor(Double factor) {
    this.factor = factor;
    return this;
  }

   /**
   * Get factor
   * @return factor
  **/
  @Schema(description = "")
  public Double getFactor() {
    return factor;
  }

  public void setFactor(Double factor) {
    this.factor = factor;
  }

  public AccountFixedIncome variableRate(Double variableRate) {
    this.variableRate = variableRate;
    return this;
  }

   /**
   * Get variableRate
   * @return variableRate
  **/
  @Schema(description = "")
  public Double getVariableRate() {
    return variableRate;
  }

  public void setVariableRate(Double variableRate) {
    this.variableRate = variableRate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountFixedIncome accountFixedIncome = (AccountFixedIncome) o;
    return Objects.equals(this.maturityDate, accountFixedIncome.maturityDate) &&
        Objects.equals(this.factor, accountFixedIncome.factor) &&
        Objects.equals(this.variableRate, accountFixedIncome.variableRate) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maturityDate, factor, variableRate, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountFixedIncome {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    maturityDate: ").append(toIndentedString(maturityDate)).append("\n");
    sb.append("    factor: ").append(toIndentedString(factor)).append("\n");
    sb.append("    variableRate: ").append(toIndentedString(variableRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
