/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
/**
* AccountsInstrument
*/
@JsonTypeInfo(
  use = JsonTypeInfo.Id.NAME,
  include = JsonTypeInfo.As.PROPERTY,
  property = "assetType")
@JsonSubTypes({
  @JsonSubTypes.Type(value = AccountCashEquivalent.class, name = "CASH_EQUIVALENT"),
  @JsonSubTypes.Type(value = AccountEquity.class, name = "EQUITY"),
  @JsonSubTypes.Type(value = AccountFixedIncome.class, name = "FIXED_INCOME"),
  @JsonSubTypes.Type(value = AccountMutualFund.class, name = "MUTUAL_FUND"),
  @JsonSubTypes.Type(value = AccountOption.class, name = "OPTION")
})
public interface AccountsInstrument {

}
