/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets amountIndicator
 */
public enum AmountIndicator {
  DOLLARS("DOLLARS"),
  SHARES("SHARES"),
  ALL_SHARES("ALL_SHARES"),
  PERCENTAGE("PERCENTAGE"),
  UNKNOWN("UNKNOWN");

  private String value;

  AmountIndicator(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static AmountIndicator fromValue(String input) {
    for (AmountIndicator b : AmountIndicator.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
