/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kcjmowright.schwab.trader.model.Commission;
import com.kcjmowright.schwab.trader.model.Fees;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CommissionAndFee
 */



public class CommissionAndFee {
  @JsonProperty("commission")
  private Commission commission = null;

  @JsonProperty("fee")
  private Fees fee = null;

  @JsonProperty("trueCommission")
  private Commission trueCommission = null;

  public CommissionAndFee commission(Commission commission) {
    this.commission = commission;
    return this;
  }

   /**
   * Get commission
   * @return commission
  **/
  @Schema(description = "")
  public Commission getCommission() {
    return commission;
  }

  public void setCommission(Commission commission) {
    this.commission = commission;
  }

  public CommissionAndFee fee(Fees fee) {
    this.fee = fee;
    return this;
  }

   /**
   * Get fee
   * @return fee
  **/
  @Schema(description = "")
  public Fees getFee() {
    return fee;
  }

  public void setFee(Fees fee) {
    this.fee = fee;
  }

  public CommissionAndFee trueCommission(Commission trueCommission) {
    this.trueCommission = trueCommission;
    return this;
  }

   /**
   * Get trueCommission
   * @return trueCommission
  **/
  @Schema(description = "")
  public Commission getTrueCommission() {
    return trueCommission;
  }

  public void setTrueCommission(Commission trueCommission) {
    this.trueCommission = trueCommission;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommissionAndFee commissionAndFee = (CommissionAndFee) o;
    return Objects.equals(this.commission, commissionAndFee.commission) &&
        Objects.equals(this.fee, commissionAndFee.fee) &&
        Objects.equals(this.trueCommission, commissionAndFee.trueCommission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commission, fee, trueCommission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommissionAndFee {\n");
    
    sb.append("    commission: ").append(toIndentedString(commission)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("    trueCommission: ").append(toIndentedString(trueCommission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
