/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kcjmowright.schwab.trader.model.CommissionLeg;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Commission
 */



public class Commission {
  @JsonProperty("commissionLegs")
  private List<CommissionLeg> commissionLegs = null;

  public Commission commissionLegs(List<CommissionLeg> commissionLegs) {
    this.commissionLegs = commissionLegs;
    return this;
  }

  public Commission addCommissionLegsItem(CommissionLeg commissionLegsItem) {
    if (this.commissionLegs == null) {
      this.commissionLegs = new ArrayList<>();
    }
    this.commissionLegs.add(commissionLegsItem);
    return this;
  }

   /**
   * Get commissionLegs
   * @return commissionLegs
  **/
  @Schema(description = "")
  public List<CommissionLeg> getCommissionLegs() {
    return commissionLegs;
  }

  public void setCommissionLegs(List<CommissionLeg> commissionLegs) {
    this.commissionLegs = commissionLegs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Commission commission = (Commission) o;
    return Objects.equals(this.commissionLegs, commission.commissionLegs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commissionLegs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Commission {\n");
    
    sb.append("    commissionLegs: ").append(toIndentedString(commissionLegs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
