/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets duration
 */
public enum Duration {
  DAY("DAY"),
  GOOD_TILL_CANCEL("GOOD_TILL_CANCEL"),
  FILL_OR_KILL("FILL_OR_KILL"),
  IMMEDIATE_OR_CANCEL("IMMEDIATE_OR_CANCEL"),
  END_OF_WEEK("END_OF_WEEK"),
  END_OF_MONTH("END_OF_MONTH"),
  NEXT_END_OF_MONTH("NEXT_END_OF_MONTH"),
  UNKNOWN("UNKNOWN");

  private String value;

  Duration(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Duration fromValue(String input) {
    for (Duration b : Duration.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
