/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kcjmowright.schwab.trader.model.FeeValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * FeeLeg
 */



public class FeeLeg {
  @JsonProperty("feeValues")
  private List<FeeValue> feeValues = null;

  public FeeLeg feeValues(List<FeeValue> feeValues) {
    this.feeValues = feeValues;
    return this;
  }

  public FeeLeg addFeeValuesItem(FeeValue feeValuesItem) {
    if (this.feeValues == null) {
      this.feeValues = new ArrayList<>();
    }
    this.feeValues.add(feeValuesItem);
    return this;
  }

   /**
   * Get feeValues
   * @return feeValues
  **/
  @Schema(description = "")
  public List<FeeValue> getFeeValues() {
    return feeValues;
  }

  public void setFeeValues(List<FeeValue> feeValues) {
    this.feeValues = feeValues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeeLeg feeLeg = (FeeLeg) o;
    return Objects.equals(this.feeValues, feeLeg.feeValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feeValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeeLeg {\n");
    
    sb.append("    feeValues: ").append(toIndentedString(feeValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
