/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kcjmowright.schwab.trader.model.FeeLeg;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Fees
 */



public class Fees {
  @JsonProperty("feeLegs")
  private List<FeeLeg> feeLegs = null;

  public Fees feeLegs(List<FeeLeg> feeLegs) {
    this.feeLegs = feeLegs;
    return this;
  }

  public Fees addFeeLegsItem(FeeLeg feeLegsItem) {
    if (this.feeLegs == null) {
      this.feeLegs = new ArrayList<>();
    }
    this.feeLegs.add(feeLegsItem);
    return this;
  }

   /**
   * Get feeLegs
   * @return feeLegs
  **/
  @Schema(description = "")
  public List<FeeLeg> getFeeLegs() {
    return feeLegs;
  }

  public void setFeeLegs(List<FeeLeg> feeLegs) {
    this.feeLegs = feeLegs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fees fees = (Fees) o;
    return Objects.equals(this.feeLegs, fees.feeLegs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feeLegs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fees {\n");
    
    sb.append("    feeLegs: ").append(toIndentedString(feeLegs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
