/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Offer
 */



public class Offer {
  @JsonProperty("level2Permissions")
  private Boolean level2Permissions = false;

  @JsonProperty("mktDataPermission")
  private String mktDataPermission = null;

  public Offer level2Permissions(Boolean level2Permissions) {
    this.level2Permissions = level2Permissions;
    return this;
  }

   /**
   * Get level2Permissions
   * @return level2Permissions
  **/
  @Schema(description = "")
  public Boolean isLevel2Permissions() {
    return level2Permissions;
  }

  public void setLevel2Permissions(Boolean level2Permissions) {
    this.level2Permissions = level2Permissions;
  }

  public Offer mktDataPermission(String mktDataPermission) {
    this.mktDataPermission = mktDataPermission;
    return this;
  }

   /**
   * Get mktDataPermission
   * @return mktDataPermission
  **/
  @Schema(description = "")
  public String getMktDataPermission() {
    return mktDataPermission;
  }

  public void setMktDataPermission(String mktDataPermission) {
    this.mktDataPermission = mktDataPermission;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Offer offer = (Offer) o;
    return Objects.equals(this.level2Permissions, offer.level2Permissions) &&
        Objects.equals(this.mktDataPermission, offer.mktDataPermission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(level2Permissions, mktDataPermission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Offer {\n");
    
    sb.append("    level2Permissions: ").append(toIndentedString(level2Permissions)).append("\n");
    sb.append("    mktDataPermission: ").append(toIndentedString(mktDataPermission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
