/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kcjmowright.schwab.trader.model.OrderValidationDetail;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * OrderValidationResult
 */



public class OrderValidationResult {
  @JsonProperty("alerts")
  private List<OrderValidationDetail> alerts = null;

  @JsonProperty("accepts")
  private List<OrderValidationDetail> accepts = null;

  @JsonProperty("rejects")
  private List<OrderValidationDetail> rejects = null;

  @JsonProperty("reviews")
  private List<OrderValidationDetail> reviews = null;

  @JsonProperty("warns")
  private List<OrderValidationDetail> warns = null;

  public OrderValidationResult alerts(List<OrderValidationDetail> alerts) {
    this.alerts = alerts;
    return this;
  }

  public OrderValidationResult addAlertsItem(OrderValidationDetail alertsItem) {
    if (this.alerts == null) {
      this.alerts = new ArrayList<>();
    }
    this.alerts.add(alertsItem);
    return this;
  }

   /**
   * Get alerts
   * @return alerts
  **/
  @Schema(description = "")
  public List<OrderValidationDetail> getAlerts() {
    return alerts;
  }

  public void setAlerts(List<OrderValidationDetail> alerts) {
    this.alerts = alerts;
  }

  public OrderValidationResult accepts(List<OrderValidationDetail> accepts) {
    this.accepts = accepts;
    return this;
  }

  public OrderValidationResult addAcceptsItem(OrderValidationDetail acceptsItem) {
    if (this.accepts == null) {
      this.accepts = new ArrayList<>();
    }
    this.accepts.add(acceptsItem);
    return this;
  }

   /**
   * Get accepts
   * @return accepts
  **/
  @Schema(description = "")
  public List<OrderValidationDetail> getAccepts() {
    return accepts;
  }

  public void setAccepts(List<OrderValidationDetail> accepts) {
    this.accepts = accepts;
  }

  public OrderValidationResult rejects(List<OrderValidationDetail> rejects) {
    this.rejects = rejects;
    return this;
  }

  public OrderValidationResult addRejectsItem(OrderValidationDetail rejectsItem) {
    if (this.rejects == null) {
      this.rejects = new ArrayList<>();
    }
    this.rejects.add(rejectsItem);
    return this;
  }

   /**
   * Get rejects
   * @return rejects
  **/
  @Schema(description = "")
  public List<OrderValidationDetail> getRejects() {
    return rejects;
  }

  public void setRejects(List<OrderValidationDetail> rejects) {
    this.rejects = rejects;
  }

  public OrderValidationResult reviews(List<OrderValidationDetail> reviews) {
    this.reviews = reviews;
    return this;
  }

  public OrderValidationResult addReviewsItem(OrderValidationDetail reviewsItem) {
    if (this.reviews == null) {
      this.reviews = new ArrayList<>();
    }
    this.reviews.add(reviewsItem);
    return this;
  }

   /**
   * Get reviews
   * @return reviews
  **/
  @Schema(description = "")
  public List<OrderValidationDetail> getReviews() {
    return reviews;
  }

  public void setReviews(List<OrderValidationDetail> reviews) {
    this.reviews = reviews;
  }

  public OrderValidationResult warns(List<OrderValidationDetail> warns) {
    this.warns = warns;
    return this;
  }

  public OrderValidationResult addWarnsItem(OrderValidationDetail warnsItem) {
    if (this.warns == null) {
      this.warns = new ArrayList<>();
    }
    this.warns.add(warnsItem);
    return this;
  }

   /**
   * Get warns
   * @return warns
  **/
  @Schema(description = "")
  public List<OrderValidationDetail> getWarns() {
    return warns;
  }

  public void setWarns(List<OrderValidationDetail> warns) {
    this.warns = warns;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderValidationResult orderValidationResult = (OrderValidationResult) o;
    return Objects.equals(this.alerts, orderValidationResult.alerts) &&
        Objects.equals(this.accepts, orderValidationResult.accepts) &&
        Objects.equals(this.rejects, orderValidationResult.rejects) &&
        Objects.equals(this.reviews, orderValidationResult.reviews) &&
        Objects.equals(this.warns, orderValidationResult.warns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alerts, accepts, rejects, reviews, warns);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderValidationResult {\n");
    
    sb.append("    alerts: ").append(toIndentedString(alerts)).append("\n");
    sb.append("    accepts: ").append(toIndentedString(accepts)).append("\n");
    sb.append("    rejects: ").append(toIndentedString(rejects)).append("\n");
    sb.append("    reviews: ").append(toIndentedString(reviews)).append("\n");
    sb.append("    warns: ").append(toIndentedString(warns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
