/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets orderType
 */
public enum OrderType {
  MARKET("MARKET"),
  LIMIT("LIMIT"),
  STOP("STOP"),
  STOP_LIMIT("STOP_LIMIT"),
  TRAILING_STOP("TRAILING_STOP"),
  CABINET("CABINET"),
  NON_MARKETABLE("NON_MARKETABLE"),
  MARKET_ON_CLOSE("MARKET_ON_CLOSE"),
  EXERCISE("EXERCISE"),
  TRAILING_STOP_LIMIT("TRAILING_STOP_LIMIT"),
  NET_DEBIT("NET_DEBIT"),
  NET_CREDIT("NET_CREDIT"),
  NET_ZERO("NET_ZERO"),
  LIMIT_ON_CLOSE("LIMIT_ON_CLOSE"),
  UNKNOWN("UNKNOWN");

  private String value;

  OrderType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static OrderType fromValue(String input) {
    for (OrderType b : OrderType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
