/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets requestedDestination
 */
public enum RequestedDestination {
  INET("INET"),
  ECN_ARCA("ECN_ARCA"),
  CBOE("CBOE"),
  AMEX("AMEX"),
  PHLX("PHLX"),
  ISE("ISE"),
  BOX("BOX"),
  NYSE("NYSE"),
  NASDAQ("NASDAQ"),
  BATS("BATS"),
  C2("C2"),
  AUTO("AUTO");

  private String value;

  RequestedDestination(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static RequestedDestination fromValue(String input) {
    for (RequestedDestination b : RequestedDestination.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
