/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets specialInstruction
 */
public enum SpecialInstruction {
  ALL_OR_NONE("ALL_OR_NONE"),
  DO_NOT_REDUCE("DO_NOT_REDUCE"),
  ALL_OR_NONE_DO_NOT_REDUCE("ALL_OR_NONE_DO_NOT_REDUCE");

  private String value;

  SpecialInstruction(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SpecialInstruction fromValue(String input) {
    for (SpecialInstruction b : SpecialInstruction.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
