/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * StreamerInfo
 */



public class StreamerInfo {
  @JsonProperty("streamerSocketUrl")
  private String streamerSocketUrl = null;

  @JsonProperty("schwabClientCustomerId")
  private String schwabClientCustomerId = null;

  @JsonProperty("schwabClientCorrelId")
  private String schwabClientCorrelId = null;

  @JsonProperty("schwabClientChannel")
  private String schwabClientChannel = null;

  @JsonProperty("schwabClientFunctionId")
  private String schwabClientFunctionId = null;

  public StreamerInfo streamerSocketUrl(String streamerSocketUrl) {
    this.streamerSocketUrl = streamerSocketUrl;
    return this;
  }

   /**
   * Get streamerSocketUrl
   * @return streamerSocketUrl
  **/
  @Schema(description = "")
  public String getStreamerSocketUrl() {
    return streamerSocketUrl;
  }

  public void setStreamerSocketUrl(String streamerSocketUrl) {
    this.streamerSocketUrl = streamerSocketUrl;
  }

  public StreamerInfo schwabClientCustomerId(String schwabClientCustomerId) {
    this.schwabClientCustomerId = schwabClientCustomerId;
    return this;
  }

   /**
   * Get schwabClientCustomerId
   * @return schwabClientCustomerId
  **/
  @Schema(description = "")
  public String getSchwabClientCustomerId() {
    return schwabClientCustomerId;
  }

  public void setSchwabClientCustomerId(String schwabClientCustomerId) {
    this.schwabClientCustomerId = schwabClientCustomerId;
  }

  public StreamerInfo schwabClientCorrelId(String schwabClientCorrelId) {
    this.schwabClientCorrelId = schwabClientCorrelId;
    return this;
  }

   /**
   * Get schwabClientCorrelId
   * @return schwabClientCorrelId
  **/
  @Schema(description = "")
  public String getSchwabClientCorrelId() {
    return schwabClientCorrelId;
  }

  public void setSchwabClientCorrelId(String schwabClientCorrelId) {
    this.schwabClientCorrelId = schwabClientCorrelId;
  }

  public StreamerInfo schwabClientChannel(String schwabClientChannel) {
    this.schwabClientChannel = schwabClientChannel;
    return this;
  }

   /**
   * Get schwabClientChannel
   * @return schwabClientChannel
  **/
  @Schema(description = "")
  public String getSchwabClientChannel() {
    return schwabClientChannel;
  }

  public void setSchwabClientChannel(String schwabClientChannel) {
    this.schwabClientChannel = schwabClientChannel;
  }

  public StreamerInfo schwabClientFunctionId(String schwabClientFunctionId) {
    this.schwabClientFunctionId = schwabClientFunctionId;
    return this;
  }

   /**
   * Get schwabClientFunctionId
   * @return schwabClientFunctionId
  **/
  @Schema(description = "")
  public String getSchwabClientFunctionId() {
    return schwabClientFunctionId;
  }

  public void setSchwabClientFunctionId(String schwabClientFunctionId) {
    this.schwabClientFunctionId = schwabClientFunctionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StreamerInfo streamerInfo = (StreamerInfo) o;
    return Objects.equals(this.streamerSocketUrl, streamerInfo.streamerSocketUrl) &&
        Objects.equals(this.schwabClientCustomerId, streamerInfo.schwabClientCustomerId) &&
        Objects.equals(this.schwabClientCorrelId, streamerInfo.schwabClientCorrelId) &&
        Objects.equals(this.schwabClientChannel, streamerInfo.schwabClientChannel) &&
        Objects.equals(this.schwabClientFunctionId, streamerInfo.schwabClientFunctionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(streamerSocketUrl, schwabClientCustomerId, schwabClientCorrelId, schwabClientChannel, schwabClientFunctionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StreamerInfo {\n");
    
    sb.append("    streamerSocketUrl: ").append(toIndentedString(streamerSocketUrl)).append("\n");
    sb.append("    schwabClientCustomerId: ").append(toIndentedString(schwabClientCustomerId)).append("\n");
    sb.append("    schwabClientCorrelId: ").append(toIndentedString(schwabClientCorrelId)).append("\n");
    sb.append("    schwabClientChannel: ").append(toIndentedString(schwabClientChannel)).append("\n");
    sb.append("    schwabClientFunctionId: ").append(toIndentedString(schwabClientFunctionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
