/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kcjmowright.schwab.trader.model.TransactionBaseInstrument;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TransactionEquity
 */



public class TransactionEquity extends TransactionBaseInstrument implements TransactionInstrument {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    COMMON_STOCK("COMMON_STOCK"),
    PREFERRED_STOCK("PREFERRED_STOCK"),
    DEPOSITORY_RECEIPT("DEPOSITORY_RECEIPT"),
    PREFERRED_DEPOSITORY_RECEIPT("PREFERRED_DEPOSITORY_RECEIPT"),
    RESTRICTED_STOCK("RESTRICTED_STOCK"),
    COMPONENT_UNIT("COMPONENT_UNIT"),
    RIGHT("RIGHT"),
    WARRANT("WARRANT"),
    CONVERTIBLE_PREFERRED_STOCK("CONVERTIBLE_PREFERRED_STOCK"),
    CONVERTIBLE_STOCK("CONVERTIBLE_STOCK"),
    LIMITED_PARTNERSHIP("LIMITED_PARTNERSHIP"),
    WHEN_ISSUED("WHEN_ISSUED"),
    UNKNOWN("UNKNOWN");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  public TransactionEquity type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionEquity transactionEquity = (TransactionEquity) o;
    return Objects.equals(this.type, transactionEquity.type) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionEquity {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
