/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets TransactionType
 */
public enum TransactionType {
  TRADE("TRADE"),
  RECEIVE_AND_DELIVER("RECEIVE_AND_DELIVER"),
  DIVIDEND_OR_INTEREST("DIVIDEND_OR_INTEREST"),
  ACH_RECEIPT("ACH_RECEIPT"),
  ACH_DISBURSEMENT("ACH_DISBURSEMENT"),
  CASH_RECEIPT("CASH_RECEIPT"),
  CASH_DISBURSEMENT("CASH_DISBURSEMENT"),
  ELECTRONIC_FUND("ELECTRONIC_FUND"),
  WIRE_OUT("WIRE_OUT"),
  WIRE_IN("WIRE_IN"),
  JOURNAL("JOURNAL"),
  MEMORANDUM("MEMORANDUM"),
  MARGIN_CALL("MARGIN_CALL"),
  MONEY_MARKET("MONEY_MARKET"),
  SMA_ADJUSTMENT("SMA_ADJUSTMENT");

  private String value;

  TransactionType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TransactionType fromValue(String input) {
    for (TransactionType b : TransactionType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
