/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * UserPreferenceAccount
 */



public class UserPreferenceAccount {
  @JsonProperty("accountNumber")
  private String accountNumber = null;

  @JsonProperty("primaryAccount")
  private Boolean primaryAccount = false;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("nickName")
  private String nickName = null;

  @JsonProperty("accountColor")
  private String accountColor = null;

  @JsonProperty("displayAcctId")
  private String displayAcctId = null;

  @JsonProperty("autoPositionEffect")
  private Boolean autoPositionEffect = false;

  public UserPreferenceAccount accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @Schema(description = "")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public UserPreferenceAccount primaryAccount(Boolean primaryAccount) {
    this.primaryAccount = primaryAccount;
    return this;
  }

   /**
   * Get primaryAccount
   * @return primaryAccount
  **/
  @Schema(description = "")
  public Boolean isPrimaryAccount() {
    return primaryAccount;
  }

  public void setPrimaryAccount(Boolean primaryAccount) {
    this.primaryAccount = primaryAccount;
  }

  public UserPreferenceAccount type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public UserPreferenceAccount nickName(String nickName) {
    this.nickName = nickName;
    return this;
  }

   /**
   * Get nickName
   * @return nickName
  **/
  @Schema(description = "")
  public String getNickName() {
    return nickName;
  }

  public void setNickName(String nickName) {
    this.nickName = nickName;
  }

  public UserPreferenceAccount accountColor(String accountColor) {
    this.accountColor = accountColor;
    return this;
  }

   /**
   * Green | Blue
   * @return accountColor
  **/
  @Schema(description = "Green | Blue")
  public String getAccountColor() {
    return accountColor;
  }

  public void setAccountColor(String accountColor) {
    this.accountColor = accountColor;
  }

  public UserPreferenceAccount displayAcctId(String displayAcctId) {
    this.displayAcctId = displayAcctId;
    return this;
  }

   /**
   * Get displayAcctId
   * @return displayAcctId
  **/
  @Schema(description = "")
  public String getDisplayAcctId() {
    return displayAcctId;
  }

  public void setDisplayAcctId(String displayAcctId) {
    this.displayAcctId = displayAcctId;
  }

  public UserPreferenceAccount autoPositionEffect(Boolean autoPositionEffect) {
    this.autoPositionEffect = autoPositionEffect;
    return this;
  }

   /**
   * Get autoPositionEffect
   * @return autoPositionEffect
  **/
  @Schema(description = "")
  public Boolean isAutoPositionEffect() {
    return autoPositionEffect;
  }

  public void setAutoPositionEffect(Boolean autoPositionEffect) {
    this.autoPositionEffect = autoPositionEffect;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserPreferenceAccount userPreferenceAccount = (UserPreferenceAccount) o;
    return Objects.equals(this.accountNumber, userPreferenceAccount.accountNumber) &&
        Objects.equals(this.primaryAccount, userPreferenceAccount.primaryAccount) &&
        Objects.equals(this.type, userPreferenceAccount.type) &&
        Objects.equals(this.nickName, userPreferenceAccount.nickName) &&
        Objects.equals(this.accountColor, userPreferenceAccount.accountColor) &&
        Objects.equals(this.displayAcctId, userPreferenceAccount.displayAcctId) &&
        Objects.equals(this.autoPositionEffect, userPreferenceAccount.autoPositionEffect);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountNumber, primaryAccount, type, nickName, accountColor, displayAcctId, autoPositionEffect);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserPreferenceAccount {\n");
    
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    primaryAccount: ").append(toIndentedString(primaryAccount)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    nickName: ").append(toIndentedString(nickName)).append("\n");
    sb.append("    accountColor: ").append(toIndentedString(accountColor)).append("\n");
    sb.append("    displayAcctId: ").append(toIndentedString(displayAcctId)).append("\n");
    sb.append("    autoPositionEffect: ").append(toIndentedString(autoPositionEffect)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
