/*
 * Trader API - Account Access and User Preferences
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * OpenAPI spec version: 1.0.0
 * Contact: TraderAPI@Schwab.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kcjmowright.schwab.trader.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * UserDetails
 */


@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "activityType", visible = true )
@JsonSubTypes({
})

public class UserDetails {
  @JsonProperty("cdDomainId")
  private String cdDomainId = null;

  @JsonProperty("login")
  private String login = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    ADVISOR_USER("ADVISOR_USER"),
    BROKER_USER("BROKER_USER"),
    CLIENT_USER("CLIENT_USER"),
    SYSTEM_USER("SYSTEM_USER"),
    UNKNOWN("UNKNOWN");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("userId")
  private Long userId = null;

  @JsonProperty("systemUserName")
  private String systemUserName = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("brokerRepCode")
  private String brokerRepCode = null;

  public UserDetails cdDomainId(String cdDomainId) {
    this.cdDomainId = cdDomainId;
    return this;
  }

   /**
   * Get cdDomainId
   * @return cdDomainId
  **/
  @Schema(description = "")
  public String getCdDomainId() {
    return cdDomainId;
  }

  public void setCdDomainId(String cdDomainId) {
    this.cdDomainId = cdDomainId;
  }

  public UserDetails login(String login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  @Schema(description = "")
  public String getLogin() {
    return login;
  }

  public void setLogin(String login) {
    this.login = login;
  }

  public UserDetails type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public UserDetails userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(description = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public UserDetails systemUserName(String systemUserName) {
    this.systemUserName = systemUserName;
    return this;
  }

   /**
   * Get systemUserName
   * @return systemUserName
  **/
  @Schema(description = "")
  public String getSystemUserName() {
    return systemUserName;
  }

  public void setSystemUserName(String systemUserName) {
    this.systemUserName = systemUserName;
  }

  public UserDetails firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @Schema(description = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public UserDetails lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @Schema(description = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public UserDetails brokerRepCode(String brokerRepCode) {
    this.brokerRepCode = brokerRepCode;
    return this;
  }

   /**
   * Get brokerRepCode
   * @return brokerRepCode
  **/
  @Schema(description = "")
  public String getBrokerRepCode() {
    return brokerRepCode;
  }

  public void setBrokerRepCode(String brokerRepCode) {
    this.brokerRepCode = brokerRepCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDetails userDetails = (UserDetails) o;
    return Objects.equals(this.cdDomainId, userDetails.cdDomainId) &&
        Objects.equals(this.login, userDetails.login) &&
        Objects.equals(this.type, userDetails.type) &&
        Objects.equals(this.userId, userDetails.userId) &&
        Objects.equals(this.systemUserName, userDetails.systemUserName) &&
        Objects.equals(this.firstName, userDetails.firstName) &&
        Objects.equals(this.lastName, userDetails.lastName) &&
        Objects.equals(this.brokerRepCode, userDetails.brokerRepCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cdDomainId, login, type, userId, systemUserName, firstName, lastName, brokerRepCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDetails {\n");
    
    sb.append("    cdDomainId: ").append(toIndentedString(cdDomainId)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    systemUserName: ").append(toIndentedString(systemUserName)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    brokerRepCode: ").append(toIndentedString(brokerRepCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
